[base]
log_level = "DEBUG"
debug = false
"classAbilityBind" = "v"
"unchargedMeleeBind" = "c"
"shadowdiveBind" = "x"
"finisherBind" = "g"
"emoteBind" = "down" # can be changed to whatever emote slot you want just change down to up/left/right


[1440p]
"bossOnScreenCoords" = [-42, -40] # on screen coords of boss
"leftRotationDuration" = 0.5 # duration camera turns left after finisher
"postRotationDuration" = 1.83 # duration to walk forward after camera turns left

"adOnScreenCoord" = [188, 72] # coord of where to look to shoot ad for finisher
"adSpawnWaitDuration" = 5.805 # how long to wait for ads to spawn

"cameraEmotePerpectiveOne" = [-850, 0] # where to aim for the emote to cut line of sight with ads
"persepectiveDurationOne" = 1.8 # duration of where youre aiming

"cameraEmotePerpectiveTwo" = [250, 0] # where to aim for the emote to cut line of sight with ads
"persepectiveDurationTwo" = 3 # duration of where youre aiming


[1080p]
"bossOnScreenCoords" = [-42, -40]
"leftRotationDuration" = 0.5
"postRotationDuration" = 1.83

"adOnScreenCoord" = [188, 72]
"adSpawnWaitDuration" = 5.805

"cameraEmotePerpectiveOne" = [-850, 0]
"persepectiveDurationOne" = 1.8

"cameraEmotePerpectiveTwo" = [250, 0]
"persepectiveDurationTwo" = 3
